# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Produgenesis
tagline:          'Un producto en constante creación.'
description:      'Un producto en constante creación.'
url:              https://produgenesis.com
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'produgenesis'
  url:            https://twitter.com/produgenesis

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.5.3
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/produgenesis/site

sass:
  sass_dir: _scss
  style: :compressed

# Authors

authors:
  gruncho:
    name: gruncho
    twitter: gruncho
    desc: Nací en Madrid en 1990, me dedico a proyectos en internet desde 1990 y actualmente soy diseñador y desarrollador web freelance en remoto, nací en Madrid pero ahora vivo en Vitoria-Gasteiz.
  chema:
    name: Chema
    twitter: chemanavarro28
    desc: Reference site about Lorem Ipsum, giving information on its origins, as well as a random Lipsum generator.
  enrique:
    name: Enrique
    twitter: enriqueaf
    desc: Reference site about Lorem Ipsum, giving information on its origins, as well as a random Lipsum generator.